apiVersion: v1
kind: Service
metadata:
  name: omnivoice-tts
  labels:
    app: omnivoice-tts
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: omnivoice-tts
